name: DotNetRedis - Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Check Redis Connection
      run: |
        # Wait for Redis to be healthy
        while ! redis-cli ping; do
          sleep 1
          echo "Waiting for Redis..."
        done
        echo "Redis is up and running!"
        # You can add more tests here that interact with Redis
        redis-cli set testkey "Hello from GitHub Actions!"
        redis-cli get testkey
